config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  resources :plays, only: [:show, :index, :create] do
  	collection do
      patch '/:id/reset',              to: 'plays#reset',  as: 'reset'
      put   '/:id/reset',              to: 'plays#reset'
      get   '/:id/result',             to: 'plays#result', as: 'result'
  		get   '/:id/quests',             to: 'plays#quests', as: 'quests'
  		get   '/:id/detail/:history_id', to: 'plays#detail', as: 'detail'
  	end
  	resources :histories, only: [:update]
  end
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Play.rb
class Play < ApplicationRecord
	has_many :histories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
	belongs_to :play
	paginates_per 4
	enum collect_status: {before_collect: 0, uncollect: 1, collected: 2}
end

app/models/question.rb
class Question < ApplicationRecord
	validates :quest, :answer, presence: true
	enum undisplay_switch: {display: 0, undisplay: 1}
	paginates_per 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

	def update
	    history = History.find(params[:id])
	    history.update(collect_status: params[:collect_status])
	  	play = Play.find(params[:play_id])
	  	collects = play.histories.where(collect_status: "collected")
	  	score = collects.count*2
	  	play.update(score: score)
	  	redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  def result
    @play = Play.find(params[:id])
  end

  def quests
  	@play = Play.find(params[:id])
  	@quests = @play.histories.page(params[:page])
    @answers = History.where(play_id: @play.id)
  end

  def index
  	@plays = Play.all
  end

  def show
  	@play = Play.find(params[:id])
  end

  def detail
  	@history = History.find(params[:history_id])
  end

  def create
    play = Play.new(score: params[:score])
    play.save

    # デフォルトで登録する質問
    default_questions = Question.where(id: [1,2,3,4,5,6,7,8,9,10])
    default_questions.each do |default_question|
      history = History.new(quest: default_question.quest, answer: default_question.answer, play_id: play.id, collect_status: "before_collect")
      history.save
    end

    # ランダムで登録する質問
    questions = Question.where.not(id: [1,2,3,4,5,6,7,8,9,10])
  	questions = questions.order("RANDOM()").limit(50)
  	questions.each do |question|
  		history = History.new(quest: question.quest, answer: question.answer, play_id: play.id, collect_status: "before_collect")
  		history.save
  	end
  	redirect_to quests_plays_path(play)
  end

  def reset
    play = Play.find(params[:id])
    histories = play.histories
    histories.update_all(collect_status: "before_collect")
    play.update(score: 0)
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.page(params[:page])
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:quest, :answer, :rate, :undisplay_switch)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/top.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
		</div>
		<div class="col-lg-6" style="text-align: center; padding-top: 15%;">
			<h2 style="font-size: 50px;">ようこそ</h2>
			<div class="row" style="padding-top: 10%;">
				<div class="col-lg-6">
					<%= link_to '練習を始める', {controller: "plays", action: "create", score: 0}, method: :post, class: "btn  btn-primary form-control", style: "color: #fff" %>
				</div>
				<div class="col-lg-6">
					<%= link_to "質問一覧", questions_path, class: "btn btn-success form-control", style: "color: #fff" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qustions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#Navber" aria-expanded="false">
          <span class="sr-only">ナビゲーションの切替</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Qustions', root_path, class: "navbar-brand" %>
      </div><!-- /.navbar-header -->
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="nav navbar-nav">
          <li><%= link_to 'ホーム', root_path %></li>
          <li><%= link_to '練習を始める', {controller: "plays", action: "create", score: 0}, method: :post %></li>
          <li><%= link_to '質問一覧', questions_path %></li>
          <li><%= link_to '練習履歴', plays_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
    <div style="margin-top: 50px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plays/detail.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>質問詳細</h1>
			<table class="table table-bordered" style="margin-top: 10%;">
				<tr>
					<th style="width: 20%; background-color: #000; color: #fff; text-align: right; border-top: 0;">質問:</th><td style="border-top: 0;"><%= @history.quest %></td>
				</tr>
				<tr>
					<th style="width: 20%; background-color: #000; color: #fff; text-align: right;">答え:</th><td><%= @history.answer %></td>
				</tr>
			</table>

			<%= link_to '戻る', play_path(@history.play_id), class: "btn btn-danger form-control", style: "color: #fff;" %>

		</div>
	</div>
</div>

app/views/plays/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>練習履歴一覧</h1>
			<% num = 0 %>
			<table class="table">
				<tr>
					<th>NO.</th>
					<th>日付</th>
					<th>スコア</th>
					<th></th>
				</tr>
				<% @plays.each do |play| %>
					<tr>
						<td><%= link_to "#{num+=1}回目", play_path(play) %></td>
						<td><%= play.created_at.strftime("%Y年%-m月%-d日 %-H時%M分") %></td>
						<td><%= play.score %></td>
						<td><%= link_to '練習する', quests_plays_path(play), class: "btn btn-primary form-control", style: "color: #fff;" %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/plays/quests.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>質問練習<span style="padding-left: 70%; color: red;"><%= @play.score %>/100<span></h1>
			<%= page_entries_info @quests %>
      		<% @quests.each do |quest| %>
	      		<table class="table">
			        <thead>
			          <tr>
			            <th>
			            	<%= quest.quest %>
			            	<% if quest.collect_status == "collected" %>
			            		<span style="background-color: #337AB7; color: #fff; padding: 3px;">
			            			正解
			            		</span>
			            	<% elsif quest.collect_status == "uncollect" %>
			            		<span style="background-color: #D9534F; color: #fff; padding: 3px;">
			            			不正解
			            		</span>
			            	<% else %>
			            		<span style="background-color: #666666; color: #fff; padding: 3px;">
			            			未回答
			            		</span>
			            	<% end %>
			            </th>
			          </tr>
			        </thead>
			        <tbody>
			            <tr>
			              	<td class="btn-group" style="width: 100%;">
								<button type="button" class="btn btn-default dropdown-toggle form-control" data-toggle="dropdown" aria-expanded="false">
									答え
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu" role="menu" style="padding: 5px;">
									<%= quest.answer %>
								</ul>
							</td>
			            </tr>
		        	</tbody>
		     	</table>
		     	<div class="row">
	        		<div class="col-lg-6">
	        			<%= link_to '正解', play_history_path(play_id: quest.play_id, id: quest.id, collect_status: "collected"), method: :put, remote: true, class: "btn btn-primary form-control", style: "color: #fff;" %>
	        		</div>
	        		<div class="col-lg-6">
	        			<%= link_to '不正解', play_history_path(play_id: quest.play_id, id: quest.id, collect_status: "uncollect"), method: :put, remote: true, class: "btn btn-danger form-control", style: "color: #fff;" %>
	        		</div>
		        </div>
			<% end %>
			<%= paginate @quests %>

			<% if @answers.find_by(collect_status: "before_collect") %>
			<% else %>
				<h2><%= link_to '結果を見る', result_plays_path(@play), class: "btn btn-success form-control", style: "color: #fff;" %></h2>
			<% end %>
			<%= link_to "リセットする", reset_plays_path(@play), method: :put, class: "btn btn-warning form-control", style: "color: #fff;" %>
		</div>
	</div>
</div>

app/views/plays/result.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3">
		</div>
		<div class="col-lg-6" style="text-align: center; padding-top: 15%;">
			<h2 style="font-size: 50px;">結果は、<%= @play.score %>点でした</h2>
			<div class="row" style="padding-top: 10%;">
				<div class="col-lg-6">
					<%= link_to '練習履歴へ', plays_path, class: "btn  btn-primary form-control", style: "color: #fff" %>
				</div>
				<div class="col-lg-6">
					<%= link_to "ホームへ", root_path, class: "btn btn-success form-control", style: "color: #fff" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/plays/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1><%= @play.id %>回目の質問一覧</h1>
		    <table class="table">
			    <thead>
			      <tr>
			        <th>No.</th>
			        <th>質問</th>
			        <th>回答履歴</th>
			      </tr>
			    </thead>
		    	<tbody>
			        <% num = 0 %>
			        <% @play.histories.each do |history| %>
			        	<tr>
				            <td><%= link_to num+=1, detail_plays_path(id: @play, history_id: history) %></td>
				            <td><%= link_to history.quest, detail_plays_path(id: @play, history_id: history) %></td>
				            <td style="width: 15%;"><% if history.collect_status == "collected" %>
			            		<span style="background-color: #337AB7; color: #fff; padding: 3px;">
			            			正解
			            		</span>
			            	<% elsif history.collect_status == "uncollect" %>
			            		<span style="background-color: #D9534F; color: #fff; padding: 3px;">
			            			不正解
			            		</span>
			            	<% else %>
			            		<span style="background-color: #666666; color: #fff; padding: 3px;">
			            			未回答
			            		</span>
			            	<% end %></td>
				        </tr>
			        <% end %>
			    </tbody>
		    </table>
		    <%= link_to '戻る', plays_path, class: "btn btn-danger form-control", style: "color: #fff;" %>
		</div>
	</div>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quest, "質問" %>
    <%= form.text_field :quest, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :answer, "答え" %>
    <%= form.text_area :answer, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.radio_button :undisplay_switch, "display" %>
    <%= form.label :display, "表示" %>

    <%= form.radio_button :undisplay_switch, "undisplay" %>
    <%= form.label :undisplay, "非表示" %>
  </div>

  <div class="actions">
    <%= form.submit "完了", class: " btn btn-success form-control", style: "color: #fff;" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>質問編集</h1>

			<%= render 'form', question: @question %>

			<div class="row">
				<div class="col-lg-6">
					<%= link_to '詳細', @question, class: "btn btn-primary form-control", style: "color: #fff;" %>
				</div>
				<div class="col-lg-6">
					<%= link_to '戻る', questions_path, class: "btn btn-danger form-control", style: "color: #fff;" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/questions/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <p id="notice"><%= notice %></p>

      <h1>質問一覧</h1>
      <%= page_entries_info @questions %>
      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>質問</th>
            <th>表示/非表示</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% num = 0 %>
          <% @questions.each do |question| %>
            <tr>
              <td><%= num+=1 %></td>
              <td><%= link_to question.quest, question_path(question) %></td>
              <td><%= question.undisplay_switch_i18n %></td>
              <td><%= link_to '詳細', question %></td>
              <td><%= link_to '編集', edit_question_path(question) %></td>
              <td><%= link_to '削除', question, method: :delete, data: { confirm: '本当に削除してもよろしいですか?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @questions %>
      <br>

      <%= link_to '質問を登録する', new_question_path, class: "btn btn-success form-control", style: "color: #fff;" %>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>質問新規作成</h1>

			<%= render 'form', question: @question %>

			<%= link_to '戻る', questions_path, class: "btn btn-danger form-control", style: "color: #fff;" %>
		</div>
	</div>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1>質問詳細</h1>
			<p id="notice"><%= notice %></p>
			<table class="table table-bordered" style="margin-top: 10%;">
				<tr>
					<th style="width: 20%; background-color: #000; color: #fff; text-align: right; border-top: 0;">質問:</th><td style="border-top: 0;"><%= @question.quest %></td>
				</tr>
				<tr>
					<th style="width: 20%; background-color: #000; color: #fff; text-align: right;">答え:</th><td><%= @question.answer %></td>
				</tr>
				<tr>
					<th style="width: 20%; background-color: #000; color: #fff; text-align: right;">表示/非表示</th><td><%= @question.undisplay_switch_i18n %></td>
				</tr>
			</table>
			<div class="row">
				<div class="col-lg-6">
					<%= link_to '編集', edit_question_path(@question), class: "btn btn-primary form-control", style: "color: #fff;" %>
				</div>
				<div class="col-lg-6">
					<%= link_to '戻る', questions_path, class: "btn btn-danger form-control", style: "color: #fff;" %>
				</div>
			</div>
		</div>
	</div>
</div>